### ISSUE TITLE
Nightly e-mails not sending

### ISSUE THREAD

**Issue by jdfergason** [jdfergason/pv-api#1]
2021-05-07T12:00:18.014798+00:00 app[scheduler.3917]: time="2021-05-07T12:00:18Z" level=info msg="Database migrated"
2021-05-07T12:00:20.673303+00:00 app[scheduler.3917]: time="2021-05-07T12:00:20Z" level=info msg="Initialized data framework"
2021-05-07T12:00:20.673368+00:00 app[scheduler.3917]: time="2021-05-07T12:00:20Z" level=info msg="Initialized strategy map"
2021-05-07T12:00:20.682103+00:00 app[scheduler.3917]: time="2021-05-07T12:00:20Z" level=info msg="Got saved portfolios" NumPortfolios=22
2021-05-07T12:00:20.682781+00:00 app[scheduler.3917]: time="2021-05-07T12:00:20Z" level=info msg="Computing portfolio performance" Portfolio=296a2da1-a2c9-4c25-b8a3-628bc6337bf9
2021-05-07T12:00:20.682816+00:00 app[scheduler.3917]: time="2021-05-07T12:00:20Z" level=info msg="Requesting user from auth0" UserId="auth0|604174f3bd1ee3006a61019e"
2021-05-07T12:00:21.534303+00:00 app[scheduler.3917]: panic: different number of rows in series
2021-05-07T12:00:21.534313+00:00 app[scheduler.3917]: 
2021-05-07T12:00:21.534319+00:00 app[scheduler.3917]: goroutine 1 [running]:
2021-05-07T12:00:21.534440+00:00 app[scheduler.3917]: github.com/rocketlaunchr/dataframe-go.NewDataFrame(0xc00020e600, 0x16, 0x18, 0x0)
2021-05-07T12:00:21.534445+00:00 app[scheduler.3917]: /tmp/codon/tmp/cache/go-path/pkg/mod/github.com/rocketlaunchr/dataframe-go@v0.0.0-20201007021539-67b046771f0b/dataframe.go:38 +0x425
2021-05-07T12:00:21.534525+00:00 app[scheduler.3917]: main/strategies.(*AcceleratingDualMomentum).computeScores(0xc0000220f0, 0xc0002c0000, 0x0)
2021-05-07T12:00:21.534546+00:00 app[scheduler.3917]: /tmp/build_6dc37e84/strategies/adm.go:242 +0xd1e
2021-05-07T12:00:21.534640+00:00 app[scheduler.3917]: main/strategies.(*AcceleratingDualMomentum).Compute(0xc0000220f0, 0xc0002c0000, 0xc0000220f0, 0x0, 0x0)
2021-05-07T12:00:21.534651+00:00 app[scheduler.3917]: /tmp/build_6dc37e84/strategies/adm.go:283 +0x10e
2021-05-07T12:00:21.534831+00:00 app[scheduler.3917]: main.computePortfolioPerformance(0xc00055c2a0, 0x39eb4e9b, 0xed825d150, 0xc0001c0690, 0x1, 0x20, 0x1)
2021-05-07T12:00:21.534837+00:00 app[scheduler.3917]: /tmp/build_6dc37e84/cmd/notifier/main.go:119 +0x64c
2021-05-07T12:00:21.534894+00:00 app[scheduler.3917]: main.main()
2021-05-07T12:00:21.535028+00:00 app[scheduler.3917]: /tmp/build_6dc37e84/cmd/notifier/main.go:386 +0x71a
2021-05-07T12:00:21.591230+00:00 heroku[scheduler.3917]: Process exited with status 2
2021-05-07T12:00:21.700212+00:00 heroku[scheduler.3917]: State changed from up to complete

**Comment by jdfergason** [comment]
This looks like data alignment issue with the risk free rate again.

**Comment by jdfergason** [comment]
Risk free rate has been fixed in the beta version
